version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

services:
  mongodb:
    << : *default-opts
    image: ${SIMVA_MONGODB_IMAGE:-mongo}:${SIMVA_MONGODB_VERSION:-4.2.8}
    networks:
      traefik_services:
        aliases:
          - ${SIMVA_MONGO_HOST_SUBDOMAIN:-simva-mongo}.${SIMVA_INTERNAL_DOMAIN:-internal.test}

  mongoku:
    << : *default-opts
    image: ${SIMVA_MONGOKU_UI_IMAGE:-huggingface/mongoku}:${SIMVA_MONGOKU_UI_VERSION:-latest}
    depends_on:
      - mongodb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SIMVA_BIN_HOME}/wait-available.sh:/bin/wait-available.sh:ro
    entrypoint: bash -c "/bin/wait-available.sh 'Mongo DB' '${SIMVA_MONGO_HOST_SUBDOMAIN:-simva-mongo}.${SIMVA_INTERNAL_DOMAIN:-internal.test}:27017' 'false' 'false' && /app/docker-run.sh"
    environment:
      MONGOKU_DEFAULT_HOST: "mongodb://${SIMVA_MONGO_HOST_SUBDOMAIN:-simva-mongo}.${SIMVA_INTERNAL_DOMAIN:-internal.test}:27017"
      SIMVA_MAX_RETRIES: ${SIMVA_MAX_RETRIES:-20}
      SIMVA_WAIT_TIME: ${SIMVA_WAIT_TIME:-15}
    restart: unless-stopped
    networks:
      default:
        aliases:
          - ${SIMVA_MONGO_UI_HOST_SUBDOMAIN:-simva-mongo-ui}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - ${SIMVA_MONGO_UI_HOST_SUBDOMAIN:-simva-mongo-ui}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mongoku.loadbalancer.server.port=3100"
      - "traefik.http.routers.mongoku.rule=Host(`${SIMVA_MONGO_UI_HOST_SUBDOMAIN:-simva-mongo-ui}.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.mongoku.middlewares=dashboardAuth@file"
