version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

services:
  simva-api:
    build: ${SIMVA_API_GIT_REPO:-/home/vagrant/docker-stacks/data/simva/simva-api}
    restart: on-failure:${SIMVA_MAX_RETRIES:-20}
    volumes:
      - ${SIMVA_API_GIT_REPO:-/home/vagrant/docker-stacks/data/simva/simva-api}:/home/node/app/
      - /home/node/app/node_modules  # Exclude node_modules
    ports:
      - "127.0.0.1:9229:9229"
  simva-front:
    build: ${SIMVA_FRONT_GIT_REPO:-/home/vagrant/docker-stacks/data/simva/simva-front}
    restart: on-failure:${SIMVA_MAX_RETRIES:-20}
    volumes:
      - ${SIMVA_FRONT_GIT_REPO:-/home/vagrant/docker-stacks/data/simva/simva-front}:/home/node/app/
      - /home/node/app/node_modules  # Exclude node_modules
    ports:
      - "127.0.0.1:9230:9229"
  simva-trace-allocator:
    build: ${SIMVA_TRACE_ALLOCATOR_GIT_REPO:-/home/vagrant/docker-stacks/data/simva/simva-trace-allocator}
    restart: on-failure:${SIMVA_MAX_RETRIES:-20}
    volumes:
      - ${SIMVA_TRACE_ALLOCATOR_GIT_REPO:-/home/vagrant/docker-stacks/data/simva/simva-trace-allocator}:/home/node/app/
      - /home/node/app/node_modules  # Exclude node_modules
    ports:
      - "127.0.0.1:9231:9229"