version: '3.7'

volumes:
  mariadb_data:
    driver: local

networks:
  traefik_services:
    external: true

services:
  mariadb:
    image: mariadb:10.4
    volumes:
      - mariadb_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
# https://github.com/docker-library/mariadb/issues/261
# https://github.com/docker-library/mariadb/issues/262      
      - MYSQL_INITDB_SKIP_TZINFO=true
    hostname: mariadb.keycloak.internal.test
    networks:
      default:
        aliases:
          - mariadb.keycloak.internal.test

  mariadb-backup:
    image: mariadb:10.4
    volumes:
      - ./mariadb-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_HOST=mariadb.keycloak.internal.test
      - MYSQL_ROOT_PASSWORD=root
      - BACKUP_NUM_KEEP=7
      - BACKUP_FREQUENCY=1d
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        mysqldump --all-databases -h"$$MYSQL_HOST" -uroot -p"$$MYSQL_ROOT_PASSWORD" > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.sql
        (ls -t /dump/dump*.sql|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.sql)|sort|uniq -u|xargs rm -- {}
        sleep $$BACKUP_FREQUENCY
      done 
      EOF'

# XXX: Use owncloud docker images as an example of using wait-for in order to wait for MariaDB availabily before launching keycloak
  keycloak:
    image: jboss/keycloak:10.0.2
    environment:
      - DB_VENDOR=mariadb
      - DB_ADDR=mariadb.keycloak.internal.test
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mariadb
    hostname: keycloak.internal.test
    networks:
      default:
        aliases:
          - keycloak.internal.test
      traefik_services:
        aliases:
          - keycloak.internal.test
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.http.routers.keycloak.rule=Host(`sso.${DOMAIN_SUFFIX:-external.test}`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls=true"

  mail:
    image: maildev/maildev:1.1.0
    environment:
      - MAILDEV_SMTP_PORT=25
      - MAILDEV_WEB_PORT=80
    hostname: mail.keycloak.internal.test
    networks:
      default:
        aliases:
          - "mail.keycloak.internal.test"
      traefik_services:
        aliases:
          - "mail.keycloak.internal.test"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mail.loadbalancer.server.port=80"
      - "traefik.http.routers.mail.rule=Host(`mail.${DOMAIN_SUFFIX:-external.test}`)"
      - "traefik.http.routers.mail.entrypoints=websecure"
      - "traefik.http.routers.mail.tls=true"