version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

services:
  pumva:
    build: ${SIMVA_PUMVA_GIT_REPO:-/home/vagrant/docker-stacks/data/simva/pumva}
    restart: unless-stopped
    volumes:
      - ${SIMVA_PUMVA_GIT_REPO:-/home/vagrant/docker-stacks/data/simva/pumva}/src:/home/node/app/src
      - ${SIMVA_PUMVA_GIT_REPO:-/home/vagrant/docker-stacks/data/simva/pumva}/public:/home/node/app/public
      - ${SIMVA_PUMVA_GIT_REPO:-/home/vagrant/docker-stacks/data/simva/pumva}/package.json:/home/node/app/package.json
      - ${SIMVA_PUMVA_GIT_REPO:-/home/vagrant/docker-stacks/data/simva/pumva}/package-lock.json:/home/node/app/package-lock.json
      - next-cache:/home/node/app/.next/cache
      - turbo-cache:/home/node/app/.turbo
    ports:
      - "127.0.0.1:9234:9229"

volumes:
  next-cache:
  turbo-cache: