version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

networks:
  kafka_services:
    driver: bridge
    name: "${SIMVA_KAFKA_NETWORK:-kafka_services}"

services:
  minio-client:
    << : *default-opts
    image: ${SIMVA_MINIO_MC_IMAGE:-minio/mc}:${SIMVA_MINIO_MC_VERSION:-RELEASE.2024-06-01T15-03-35Z}
    entrypoint: >
      /bin/sh -c '
      if [ ! -e "/etc/ssl/certs/internal-CA.pem" ]; then
        cp /root/.mc/certs/CAs/rootCA.pem "/etc/ssl/certs/internal-CA.pem";
        cat "/etc/ssl/certs/internal-CA.pem" >> /etc/ssl/cert.pem;
      fi;
      /usr/bin/mc config host add simva-minio $${MINIO_URL} $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY} --api s3v4;
      /usr/bin/mc ready simva-minio;
      if [[ $$? -ne 0 ]]; then
        echo "Error: Unable to initialize connection to MinIO."
        exit 1
      fi;
      exec sleep inf;'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SIMVA_CONFIG_HOME:-/home/vagrant/docker-stacks/config}/minio/policies:/policies:ro
      # Add extra CA (for self-signed certificates)
      - ${SIMVA_TLS_HOME?TLS home folder required}/ca:/root/.mc/certs/CAs/
      - ${SIMVA_CONTAINER_TOOLS_HOME:-/home/vagrant/docker-stacks/container-tools}:/container-tools
      - ${SIMVA_HOME:-/home/vagrant/docker-stacks}/bin/wait-available.sh:/bin/wait-available.sh:ro
    environment:
      MINIO_SSO_HOST: "${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_EXTERNAL_DOMAIN:-external.test}:443"
      MINIO_SSO_REALM: "${SIMVA_SSO_REALM:-simva}"
      MINIO_HOST: "${SIMVA_MINIO_HOST_SUBDOMAIN:-minio}.${SIMVA_EXTERNAL_DOMAIN:-external.test}:443"
      MINIO_URL: "https://${SIMVA_MINIO_API_HOST_SUBDOMAIN:-minio-api}.${SIMVA_EXTERNAL_DOMAIN:-external.test}"
      MINIO_ACCESS_KEY: "${SIMVA_MINIO_ACCESS_KEY:-minio}"
      MINIO_SECRET_KEY: "${SIMVA_MINIO_SECRET_KEY:-secret}"
      MINIO_BUCKET: "${SIMVA_TRACES_BUCKET_NAME:-traces}"
      SIMVA_SINK_USER: "${SIMVA_KAFKA_CONNECT_SINK_USER:-simva-sink}"
      SIMVA_SINK_SECRET: "${SIMVA_KAFKA_CONNECT_SINK_SECRET:-password}"
      SIMVA_WAIT_TIME: ${SIMVA_WAIT_TIME:-10}
      SIMVA_MAX_RETRIES: ${SIMVA_MAX_RETRIES:-20}
      WAIT_TIMEOUT: ${SIMVA_WAIT_TIMEOUT:-240}
    hostname: minio-mc.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    restart: no
    networks:
      default:
        aliases:
          - minio-mc.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - minio-mc.${SIMVA_INTERNAL_DOMAIN:-internal.test}