version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

networks:
  traefik_services:
    name: "${SIMVA_SERVICE_NETWORK:-traefik_services}"
    external: true

services:
  limesurvey:
    << : *default-opts
    image: ${SIMVA_LIMESURVEY_IMAGE:-martialblog/limesurvey}:${SIMVA_LIMESURVEY_VERSION:-6-apache}
    #entrypoint:
    #  - '/bin/bash'
    #  - '-c'
    #  - '/container-tools/wait-for-it.sh -h $${DB_HOST} -p 3306 -t $${WAIT_TIMEOUT} -- /usr/local/bin/entrypoint.sh && exec apache2 -D FOREGROUND'
    environment:
      DEBUG: "${SIMVA_LIMESURVEY_DEBUG_ENTRYPOINT:-false}"
      DB_HOST: mariadb.${SIMVA_LIMESURVEY_HOST_SUBDOMAIN:-limesurvey}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      DB_NAME: ${SIMVA_LIMESURVEY_MYSQL_DATABASE:-limesurvey}
      DB_USERNAME: ${SIMVA_LIMESURVEY_MYSQL_USER:-limesurvey}
      DB_PASSWORD: ${SIMVA_LIMESURVEY_MYSQL_PASSWORD:-password}
      ADMIN_USER: ${SIMVA_LIMESURVEY_ADMIN_USER:-admin}
      ADMIN_NAME: ${SIMVA_LIMESURVEY_ADMIN_NAME:-Simva Administrator}
      ADMIN_EMAIL: "${SIMVA_LIMESURVEY_ADMIN_EMAIL_USERNAME:-lime-dev}@${SIMVA_LIMESURVEY_HOST_SUBDOMAIN:-limesurvey}.${SIMVA_EXTERNAL_DOMAIN:-external.test}"
      ADMIN_PASSWORD: ${SIMVA_LIMESURVEY_ADMIN_PASSWORD:-secret}
      PUBLIC_URL: "https://${SIMVA_LIMESURVEY_HOST_SUBDOMAIN:-limesurvey}.${SIMVA_EXTERNAL_DOMAIN:-external.test}:443"
      BASE_URL: "https://${SIMVA_LIMESURVEY_HOST_SUBDOMAIN:-limesurvey}.${SIMVA_EXTERNAL_DOMAIN:-external.test}:443"
      WAIT_TIMEOUT: ${SIMVA_WAIT_TIMEOUT:-240}
      LIMESURVEY_WEBHOOK_PLUGIN_URL: https://${SIMVA_API_HOST_SUBDOMAIN:-simva-api}.${SIMVA_EXTERNAL_DOMAIN:-external.test}/limesurvey-completion-webhooks
      LIMESURVEY_WEBHOOK_PLUGIN_DEBUG: ${SIMVA_DEBUG:-true}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SIMVA_CONFIG_HOME:-/home/vagrant/docker-stacks/config}/limesurvey/etc/config.php:/var/www/html/application/config/config.php
      - ${SIMVA_CONFIG_HOME:-/home/vagrant/docker-stacks/config}/limesurvey/etc/security.php:/var/www/html/application/config/security.php
      - ${SIMVA_DATA_HOME:-/home/vagrant/docker-stacks/data}/limesurvey/data/plugins:/var/www/html/plugins
      - ${SIMVA_DATA_HOME:-/home/vagrant/docker-stacks/data}/limesurvey/data/upload:/var/www/html/upload
      - ${SIMVA_CONTAINER_TOOLS_HOME:-/home/vagrant/docker-stacks/container-tools}:/container-tools
    restart: unless-stopped
    healthcheck:
      test: "curl -sS http://localhost:8080 || exit 1"
      interval: 60s
      timeout: 20s
      retries: 3
    hostname: ${SIMVA_LIMESURVEY_HOST_SUBDOMAIN:-limesurvey}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - ${SIMVA_LIMESURVEY_HOST_SUBDOMAIN:-limesurvey}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - ${SIMVA_LIMESURVEY_HOST_SUBDOMAIN:-limesurvey}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ls.loadbalancer.server.port=8080"
      - "traefik.http.routers.ls.rule=Host(`${SIMVA_LIMESURVEY_HOST_SUBDOMAIN:-limesurvey}.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.ls.middlewares=secHeaders@file"