version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

networks:
  traefik_services:
    name: "${SIMVA_SERVICE_NETWORK:-traefik_services}"
    external: true

services:
  limesurvey:
    << : *default-opts
    entrypoint: ["/entrypoint/limesurvey.sh"]
    command: ["apache2-foreground"]
    environment:
      DEBUG: "${SIMVA_LIMESURVEY_DEBUG_ENTRYPOINT:-false}"
      DB_HOST: mariadb.${SIMVA_LIMESURVEY_HOST_SUBDOMAIN:-limesurvey}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      DB_NAME: ${SIMVA_LIMESURVEY_MYSQL_DATABASE:-limesurvey}
      DB_USERNAME: ${SIMVA_LIMESURVEY_MYSQL_USER:-limesurvey}
      DB_PASSWORD: ${SIMVA_LIMESURVEY_MYSQL_PASSWORD:-password}
      ADMIN_USER: ${SIMVA_LIMESURVEY_ADMIN_USER:-admin}
      ADMIN_NAME: ${SIMVA_LIMESURVEY_ADMIN_NAME:-Simva Administrator}
      ADMIN_EMAIL: "${SIMVA_LIMESURVEY_ADMIN_EMAIL_USERNAME:-lime-dev}@${SIMVA_LIMESURVEY_HOST_SUBDOMAIN:-limesurvey}.${SIMVA_EXTERNAL_DOMAIN:-external.test}"
      ADMIN_PASSWORD: ${SIMVA_LIMESURVEY_ADMIN_PASSWORD:-secret}
      PUBLIC_URL: "https://${SIMVA_LIMESURVEY_HOST_SUBDOMAIN:-limesurvey}.${SIMVA_EXTERNAL_DOMAIN:-external.test}:443"
      BASE_URL: "https://${SIMVA_LIMESURVEY_HOST_SUBDOMAIN:-limesurvey}.${SIMVA_EXTERNAL_DOMAIN:-external.test}:443"
      MSMTP_HOST: "${SIMVA_MAIL_HOST_SUBDOMAIN:-mail}.${SIMVA_SSO_HOST_SUBDOMAIN:-sso}.${SIMVA_INTERNAL_DOMAIN:-internal.test}"
      MSMTP_FROM: "no-reply@${SIMVA_LIMESURVEY_HOST_SUBDOMAIN:-limesurvey}.${SIMVA_EXTERNAL_DOMAIN:-external.test}"
      WAIT_TIMEOUT: ${SIMVA_WAIT_TIMEOUT:-240}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ls_etc:/custom-config
      - ${SIMVA_DATA_HOME:-/home/vagrant/docker-stacks/data}/limesurvey/data/plugins:/var/www/html/plugins
      - ls_upload:/var/www/html/upload
      - /var/www/html/upload/themes/survey  # Exclude themes survey folder
      - /var/www/html/upload/admintheme # Exclude admintheme folder
      - ls_tmp:/var/www/html/tmp
      - /var/www/html/tmp/assets  # Exclude assets folder
      - ${SIMVA_TLS_HOME?TLS home folder required}:/root/.limesurvey/certs/:ro
      - ${SIMVA_CONTAINER_TOOLS_HOME:-/home/vagrant/docker-stacks/container-tools}:/container-tools
      - ${STACK_HOME:-/home/vagrant/docker-stacks/03-limesurvey}/etc/entrypoint.d/:/entrypoint
    restart: unless-stopped
    healthcheck:
      test: "curl -sS http://localhost:8080 || exit 1"
      interval: 60s
      timeout: 20s
      retries: 3
    depends_on:
      - mariadb
    hostname: ${SIMVA_LIMESURVEY_HOST_SUBDOMAIN:-limesurvey}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - ${SIMVA_LIMESURVEY_HOST_SUBDOMAIN:-limesurvey}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - ${SIMVA_LIMESURVEY_HOST_SUBDOMAIN:-limesurvey}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ls.loadbalancer.server.port=8080"
      - "traefik.http.routers.ls.rule=Host(`${SIMVA_LIMESURVEY_HOST_SUBDOMAIN:-limesurvey}.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"

volumes:
  ls_upload:
    external: true
  ls_tmp:
    external: true
  ls_etc:
    external: true