version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "${SIMVA_LOGGING_MAX_FILE_SIZE}"
      max-file: "${SIMVA_LOGGING_MAX_FILES}"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

networks:
  traefik_services:
    name: "${SIMVA_SERVICE_NETWORK:-traefik_services}"
    external: true

services:
  tmon-app:
    << : *default-opts
    restart: on-failure:${SIMVA_MAX_RETRIES:-20}
    hostname: ${SIMVA_TMON_HOST_DASHBOARD_SUBDOMAIN:-tmon}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - ${SIMVA_TMON_HOST_DASHBOARD_SUBDOMAIN:-tmon}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
      traefik_services:
        aliases:
          - ${SIMVA_TMON_HOST_DASHBOARD_SUBDOMAIN:-tmon}.${SIMVA_INTERNAL_DOMAIN:-internal.test}
    environment:
      REQUESTS_CA_BUNDLE: "/root/.tmon/certs/ca/rootCA.pem"
    volumes:
      - ${SIMVA_TLS_HOME?TLS home folder required}:/root/.tmon/certs/:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.tmon.loadbalancer.server.port=8050"
      - "traefik.http.routers.tmon.rule=Host(`${SIMVA_TMON_HOST_DASHBOARD_SUBDOMAIN:-tmon}.${SIMVA_EXTERNAL_DOMAIN:-external.test}`)"