version: '3.7'

volumes:
  minio_data:
    driver: local

networks:
  traefik_services:
    external: true

services:
# https://github.com/minio/minio/issues/7394#issuecomment-476552537
# https://github.com/minio/minio/blob/master/docs/sts/web-identity.md
# https://github.com/minio/minio/blob/master/docs/sts/keycloak.md
# https://github.com/minio/minio/blob/master/docs/sts/wso2.md
  minio:
    image: minio/minio:RELEASE.2020-06-03T22-13-49Z
    command: server /data
    volumes:
      - minio_data:/data
# be advised if minio is launched as a non-root user you need to change this setting
# Note too that this setting it is only needed if using a non-recognized CA (https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html#install-certificates-from-third-party-cas)
      - "./CAs:/root/.minio/certs/CAs"
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "password"
      MINIO_IDENTITY_OPENID_CLIENT_ID: "https://minio.external.test"
      MINIO_IDENTITY_OPENID_CONFIG_URL: "https://sso.external.test/auth/realms/simva/.well-known/openid-configuration"
    hostname: minio.internal.test
    dns:
      - 172.30.0.53
    networks:
      default:
        aliases:
          - minio.internal.test
      traefik_services:
        aliases:
          - minio.internal.test
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio.rule=Host(`minio.${DOMAIN_SUFFIX:-external.test}`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls=true"

# mc config host add --insecure simva-minio https://minio.${DOMAIN_SUFFIX:-external.test} minio password
# mc --debug --insecure mb simva-minio/prueba
# mc --debug --insecure ls simva-minio
# https://github.com/minio/minio/issues/7086 -> write-user-folder.json
# https://github.com/minio/minio/issues/8345 -> write-user-folder-jwt.json
#
# Not required (already configured using env variables but useful:
#   /usr/bin/mc --debug --insecure admin config set simva-minio identity_openid config_url="https://sso.external.test/auth/realms/simva/.well-known/openid-configuration" client_id="https://minio.external.test";
#   /usr/bin/mc --debug --insecure admin service restart simva-minio;
  mc:
    image: minio/mc:RELEASE.2020-05-28T23-43-36Z
    entrypoint: >
      /bin/sh -c "
      if [ ! -e '/minio-initialized' ]; then
        echo 'Waiting 30s';
        sleep 30;
        /usr/bin/mc config host add --insecure simva-minio https://minio.${DOMAIN_SUFFIX:-external.test} minio password;
        /usr/bin/mc --debug --insecure admin policy add simva-minio/ write-user-folder /policies/write-user-folder.json;
        /usr/bin/mc --debug --insecure admin policy add simva-minio/ write-user-folder-jwt /policies/write-user-folder-jwt.json;
        /usr/bin/mc --debug --insecure admin policy add simva-minio/ readonly-user-folder /policies/readonly-user-folder.json;
        /usr/bin/mc --debug --insecure admin policy add simva-minio/ readonly-user-folder-jwt /policies/readonly-user-folder-jwt.json;
        /usr/bin/mc --debug --insecure mb simva-minio/traces;
        touch /minio-initialized;
      fi
      "
    volumes:
      - ./policies:/policies:ro
    depends_on:
      - minio
    hostname: mc.internal.test
    dns:
      - 172.30.0.53
    networks:
      traefik_services:
        aliases:
          - mc.internal.test

#  kes:
#    image: minio/kes:v0.9.0
#    hostname: kes.internal.test
#    dns:
#      - 172.30.0.53
#    networks:
#      default:
#        aliases:
#          - kes.internal.test